<!DOCTYPE html>
<html>
   
   
<head>
<meta charset="utf-8">
<title>CONTACT</title>
</head>
    
    
<body>
<!-- action="index.php" method="post" -->
    
 <h1>CONTACT</h1>   
    
<form method="post">
    
<p>Nom
<input type="text" name="nom" pattern="[A-Za-z]{2,20}" title="Votre nom doit contenir entre 2 et 20 lettres" />
</p>
    
<p>Prénom
<input type="text" name="prenom" pattern="[A-Za-z]{2,20}" title="Votre nom doit contenir entre 2 et 20 lettres" />
</p>
    
<p>Promotion
<input type="text" name="promo" pattern="[1-5]{1}A" title="Votre promotion doit être sous la forme suivante :XA où X est un chiffre compris entre 1 et 5" />
</p>
    
<p>Classe
<input type="text" name="classe" pattern="[\w]{2,5}" title="Votre classe doit contenir 2 à 5 caractères"/>
</p>
    
<p>Sous-groupe
<input type="text" name="sousgroupe" pattern="[\w]{2,5}" title="Votre sous-groupe doit contenir 2 à 5 caractères" />
</p>
    
<p>Groupe d'anglais
<input type="text" name="groupeanglais" pattern="[A-Z]{1}" title="Votre groupe d'anglais doit contenir 1 lettre majuscule"/>
</p>
    
<p>Groupe LV2
<input type="text" name="groupelv2"  pattern="[A-Z]{1}[1-9]{1}" title="Votre groupe LV2 doit contenir une lettre majuscule suivie d'un chiffre"/>
</p>
    
<p>N° de téléphone
<input type="text" name="telephone" pattern="[0-9]{10}" title="Votre N° de téléphone doit contenir 10 chiffres"/>
</p>
    
<p>Adresse e-mail
<input type="email" name="mail" />
</p>

<!--    
<p>Description</p>
<textarea name="message" rows="8" cols="45">
</textarea>
<br/>
<p> Année de naissance
<select name="choix">

    <option value="choix1">1992</option>

    <option value="choix2">1993</option>

    <option value="choix3">1994</option>

    <option value="choix4">1995</option>

</select>
</p>
-->
<br/>
<input type="submit" value="Valider" />
</p>    
    
</form>
    

  
    
</body>


</html>
