<html>
    <head>
        <title>Notre première instruction </title>
        <meta charset="utf-8" />
    </head>
    <body>
        <h2>Affichage de texte avec PHP</h2>
        
        <p>
            Cette ligne a été écrite entièrement en HTML.<br />
           <b> Celle-ci a été écrite entièrement en PHP. </b>"
        </p>
    </body>
	</html>
<?php
	echo " <strong> Celle-ci a été écrite entièrement en PHP. </strong>" ;

?>